blank_issues_enabled: false
contact_links:
  - name: Share an idea or ask a question.
    url: https://github.com/Jerrie-Aries/modmail/discussions
    about: You can share your ideas or ask questions here before creating an issue.
