# -*- coding: utf-8 -*-
"""
discord.ext.commands
~~~~~~~~~~~~~~~~~~~~~

A custom extension module to facilitate creation of bot commands.

Anything here is either a reimplementation or re-export of a discord.ext.commands function or class.
This should be checked on every discord.py update.
"""

# ## DEP-WARN: Check this *every* discord.py update
# ## These MUST be imported first to avoid circular imports
# noinspection PyUnresolvedReferences
from discord.ext.commands import (
    ArgumentParsingError,
    AutoShardedBot,
    BadArgument,
    BadBoolArgument,
    BadColorArgument,
    BadColourArgument,
    BadFlagArgument,
    BadInviteArgument,
    BadLiteralArgument,
    BadUnionArgument,
    Bot,
    BotMissingAnyRole,
    BotMissingPermissions,
    BotMissingRole,
    BucketType,
    CategoryChannelConverter,
    ChannelNotFound,
    ChannelNotReadable,
    CheckAnyFailure,
    CheckFailure,
    Cog,
    CogMeta,
    ColorConverter,
    ColourConverter,
    Command,
    CommandError,
    CommandInvokeError,
    CommandNotFound,
    CommandOnCooldown,
    CommandRegistrationError,
    # renaming this as we're gonna use the name `Context`
    # for our custom class from now on
    Context as DPYContext,
    ConversionError,
    Converter,
    Cooldown,
    CooldownMapping,
    DefaultHelpCommand,
    DisabledCommand,
    DynamicCooldownMapping,
    EmojiConverter,
    EmojiNotFound,
    ExpectedClosingQuoteError,
    ExtensionAlreadyLoaded,
    ExtensionError,
    ExtensionFailed,
    ExtensionNotFound,
    ExtensionNotLoaded,
    Flag,
    FlagConverter,
    FlagError,
    GameConverter,
    Greedy,
    Group,
    GroupMixin,
    GuildChannelConverter,
    GuildConverter,
    GuildNotFound,
    GuildStickerConverter,
    GuildStickerNotFound,
    HelpCommand,
    IDConverter,
    InvalidEndOfQuotedStringError,
    InviteConverter,
    MaxConcurrency,
    MaxConcurrencyReached,
    MemberConverter,
    MemberNotFound,
    MessageConverter,
    MessageNotFound,
    MinimalHelpCommand,
    MissingAnyRole,
    MissingFlagArgument,
    MissingPermissions,
    MissingRequiredArgument,
    MissingRequiredFlag,
    MissingRole,
    NSFWChannelRequired,
    NoEntryPointError,
    NoPrivateMessage,
    NotOwner,
    ObjectConverter,
    ObjectNotFound,
    Paginator,
    PartialEmojiConversionFailure,
    PartialEmojiConverter,
    PartialMessageConverter,
    PrivateMessageOnly,
    RoleConverter,
    RoleNotFound,
    StageChannelConverter,
    TextChannelConverter,
    ThreadConverter,
    ThreadNotFound,
    TooManyArguments,
    TooManyFlags,
    UnexpectedQuoteError,
    UserConverter,
    UserInputError,
    UserNotFound,
    VoiceChannelConverter,
    after_invoke,
    before_invoke,
    bot,
    bot_has_any_role,
    bot_has_guild_permissions,
    bot_has_permissions,
    bot_has_role,
    check,
    check_any,
    clean_content,
    cog,
    command,
    context,
    converter,
    cooldown,
    cooldowns,
    core,
    dm_only,
    dynamic_cooldown,
    errors,
    flag,
    flags,
    group,
    guild_only,
    has_any_role,
    has_guild_permissions,
    has_permissions,
    has_role,
    help,
    hybrid_command,
    hybrid_group,
    is_nsfw,
    is_owner,
    max_concurrency,
    run_converters,
    view,
    when_mentioned,
    when_mentioned_or,
)


# Now we can import these after importing all modules from discord.ext.commands
from .context import Context
